### ISSUE TITLE
Create Weekly Slips by LC call number Jobs Task

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#234]
Selectors want to know books that have been cataloged by LC that have come out recently that they may not have heard of yet. @mzelesky has created a report via WorldShare Collection Manager, an OCLC project, to create data dumps of relevant records, and this job will take those datadumps and create a spreadsheet of relevant books for selectors that is easy for them to go over quickly. 

Create a rake task that can be scheduled to process LC Slips

1. Grab Current File Set from OCLC SFTP Server
    - Username & password are in LastPass - OCLC DataSync Credentials under Shared-EUS
    - Server: `filex-m1.oclc.org`
    - Directory: `/xfer/metacoll/out/ongoing/new`
    - relevant files have `MZallDLC` in filename
    - Files are added to this server weekly
2. Run LC Slips routine over new files - https://github.com/PrincetonUniversityLibrary/lib_reports/blob/main/ruby/tasks/lc_slips_combined.rb
    - Should be moved into LibJobs and made Object Oriented
    - This job currently also creates Marc files, these are not needed.
3. Produce CSV file w/ UTF8 Files for selectors
    - These files should be as easy as possible to open in Excel on a Windows machine. There have been issues in the past with character encoding, where the file was encoded with UTF-8 and Excel tried to open it using Latin1, resulting in bad diacritics. 
    - For the first stage of this project, we will use the configuration for Bobray Bordelon and Jeremy Darrington (Wayne Bivens-Tatum is not presently interested in receiving these), but we should keep in mind extensibility for more selectors in the near future. Jeremy Darrington would like his to be updated to only include the J ranges.
4. Distribute files to selectors via email (each selector gets their own report) (do under #564)

**Comment by kevinreiss** [comment]
@pdiskin @mzelesky is this still desirable?

**Comment by sandbergja** [comment]
Work together with @pdiskin and @mzelesky on fleshing out the requirements, adding the configuration files to the lib_jobs repo.

**Comment by maxkadel** [comment]
[Notes on meeting](https://docs.google.com/document/d/1NNPszeyBbRin0aJQEMLODcPiUKcdsag2pFcwFcnuTkM/edit) - @pdiskin will circle back with selectors to ensure this is still something that would be useful.

**Comment by maxkadel** [comment]
Emailed selectors 8/1/2023 to get feedback on CSVs.

**Comment by maxkadel** [comment]
Heard back from Bobray, generally positive, although interested in excluding:
- Works published by OECD (we have automatic access to all of these works)
- Works where we already own a work with the same ISBN (de-duplication)
  - This might need to be "future work", since checking against Alma is not currently something this job does.

**Comment by maxkadel** [comment]
Heard back from Jeremy, also generally positive. Requests included:
- Number of holding libraries ("useful but not critical")
- The text of the title field in native characters, not just Romanized text, since translators don't tend to work on Romanized text
- All books in the J etc. classes, but only include if they have both the keyword "political" AND are in call numbers D, F, G, H, K or U. Bobray wants books in any class that include his keywords.

**Comment by maxkadel** [comment]
Code has been merged, deployed, and is working, feedback has been ticketed.
