### ISSUE TITLE
Create AlmaKbart Job

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#68]
Send data from Alma to AccessAnywhere

**Questions**
Need more information on what data from Alma, and where to in AccessAnywhere

**Comment by kevinreiss** [comment]
@pmgreen could you fill in some details here about the current process. I believe Alma can publish to Kbart.

**Comment by pmgreen** [comment]
Basically run a simple Ruby script to:
- fetch and loop through files in the weekly (every Monday) kbart extract in $SFXLCL41/dbs/scratch
- extract the target name from each filename and add them to a combined output file
- ftp the resulting file to the access anywhere server

**Comment by kevinreiss** [comment]
@pmgreen after go live let's do a test of the Alma Kbart output. Doing this by mid-August would be ideal so the data sent out to Access Anywhere doesn't get too stale after the cutover to Alma e-resources the week of 8/2.

**Comment by pmgreen** [comment]
Alma's KBART output differs from what we provided for Access Anywhere. There are 3 fewer fields, and differing data in some fields. Investigating further.

**Comment by pmgreen** [comment]
@kevinreiss : a Nov 2018 email message from Robert McGrath at Anywhere Access lists just 3 required KBART fields:

- `print_identifier` - in Alma export
- `online_identifier` - in Alma export
- ` interface_name` - NOT in Alma export

Since 2018 we've been providing filenames (`File.basename` minus dates) as the `interface_name`. It looks like we'll probably need to run the same sort of script:
1. configure a weekly job that exports KBART for portfolios to a directory on lib-sftp
2. loop over the exported files, gathering their data and filenames
3. append filenames to existing fields (as the required `interface_name`) in a single combined csv
4. zip and push the resulting file (using their requested naming convention) to ftp.readcube.com. E.g. `EXPORT_PORTFOLIOS_PRINCETON_SFX_20210719064145.zip`

**Comment by kevinreiss** [comment]
@pmgreen what is the status of this one?

**Comment by pmgreen** [comment]
Never heard back from readcube. As far as I know, this is no longer needed.

**Comment by kevinreiss** [comment]
Ok, closing. Let me know if this needs revisiting
